name: Setup Playwright action
description: "Install Playwright browsers with caching"


runs:
  using: "composite"
  steps:
    - name: Get Playwright version
      id: get-playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(npm ls --json @playwright/test | jq --raw-output '.dependencies["@playwright/test"].version')
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

    - name: Cache playwright binaries
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ steps.get-playwright-version.outputs.PLAYWRIGHT_VERSION }}
        restore-keys: playwright-

    - name: Install playwright
      shell: bash
      run: |
        # Skip installing pacakge docs {makes the man-db trigger much faster) 
        # (I disabled `/doc` and `/info` too, just in case.)
        # ref: https://github.com/actions/runner-images/issues/10977#issuecomment-2810713336
        sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
        path-exclude /usr/share/doc/*
        path-exclude /usr/share/man/*
        path-exclude /usr/share/info/*
        EOF

        npx playwright install chromium --with-deps
