name: Dry-run Renovate

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/dry-renovate.yaml
      - renovate.json5

jobs:
  dry-run:
    runs-on: ubuntu-latest
    permissions:
      actions: read  # required for actions-timeline
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: blob:none

      - uses: cybozu/renovate-dry-run-action@v2
        with:
          config-file: renovate.json5

      - uses: Kesin11/actions-timeline@7c7e0821d38f27460f4a71ef874a1c8cf23602e4 # v2.2.6

