name: Monthly pull request metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3 1 * *'

permissions:
  issues: write
  pull-requests: read
  actions: read  # required for actions-timeline

jobs:
  build:
    name: pull request metrics
    runs-on: ubuntu-latest
    steps:
      - name: 1 ヶ月前の範囲を取得 # 例: 7 月に実行した場合、2023-06-01..2023-06-30 のようになる
        shell: bash
        id: days
        run: |
          # Calculate the first day of the previous month
          first_day=$(date -d "last month" +%Y-%m-01)

          # Calculate the last day of the previous month
          last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)
          
          #Set an environment variable with the date range
          echo "$first_day..$last_day"
          echo "last_month=$first_day..$last_day" >> "$GITHUB_OUTPUT"

      - name: Run issue-metrics tool
        uses: github/issue-metrics@6bc5254e72971dbb7462db077779f1643f772afd # v2.14.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ワークフロー実行リポジトリで
          # 先月に作られたプルリクエストを抽出
          SEARCH_QUERY: 'repo:${{ github.repository }} is:pr created:${{ steps.days.outputs.last_month }}'

      - name: Create issue
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v4.0.1
        with:
          title: Monthly pull request metrics report (${{ steps.days.outputs.last_month }})
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 251 # 最初に作った Issue を更新する。https://github.com/korosuke613/homepage-2nd/issues/251
          content-filepath: ./issue_metrics.md

      - uses: Kesin11/actions-timeline@baa62e018ca5504e2d617502ce1eacf9171e757a # v2.0.1
