name: Scraping by Algolia

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "scraping"

permissions:
  actions: read  # required for actions-timeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: blob:none
      - name: Scraping
        run: |
          docker run \
            --env "CONFIG=$(cat ./algolia.json | jq -r tostring)" \
            --env "APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }}" \
            --env "API_KEY=${{ secrets.ALGOLIA_API_KEY }}" \
            algolia/docsearch-scraper

      - uses: Kesin11/actions-timeline@7c7e0821d38f27460f4a71ef874a1c8cf23602e4 # v2.2.6
        if: github.event.workflow == '.github/workflows/scraping.yaml'
